-- Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
-- SPDX-License-Identifier: MIT-0

CREATE OR REPLACE EXTERNAL FUNCTION public.f_calculate_route(DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION, DOUBLE PRECISION)
RETURNS VARCHAR
STABLE
LAMBDA '<ROUTE_LAMBDA_FUNCTION_NAME>'
IAM_ROLE '<REDSHIFT_LAMBDA_IAM_ROLE>';