# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrackingSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TrackingSample
  pod 'AWSMobileClient'
  pod 'AWSCore'
  pod 'AWSLocation'
  
  target 'TrackingSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrackingSampleUITests' do
    # Pods for testing
  end

end
