/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0ff3fa97-f987-4dfa-9605-5c3a693b7875",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_XZVP1z29M",
    "aws_user_pools_web_client_id": "5qmol0hjrdpi6u6s32n64pi9vo",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "geo": {
        "amazon_location_service": {
            "region": "us-east-1",
            "maps": {
                "items": {
                    "esristreet-dev": {
                        "style": "VectorEsriStreets"
                    },
                    "esrinavigation-dev": {
                        "style": "VectorEsriNavigation"
                    },
                    "esridarkgray-dev": {
                        "style": "VectorEsriDarkGrayCanvas"
                    },
                    "esrilightgray-dev": {
                        "style": "VectorEsriLightGrayCanvas"
                    },
                    "esriimagery-dev": {
                        "style": "RasterEsriImagery"
                    },
                    "hereexolore-dev": {
                        "style": "VectorHereExplore"
                    },
                    "heretruck-dev": {
                        "style": "VectorHereExploreTruck"
                    },
                    "hereberlin-dev": {
                        "style": "VectorHereBerlin"
                    },
                    "esrilight-dev": {
                        "style": "VectorEsriTopographic"
                    }
                },
                "default": "esrilight-dev"
            },
            "search_indices": {
                "items": [
                    "placeindex25da5c3c-dev"
                ],
                "default": "placeindex25da5c3c-dev"
            }
        }
    }
};


export default awsmobile;
