/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5135668d-a759-4cb6-9459-4dedcf715f5e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4OjbSpSTc",
    "aws_user_pools_web_client_id": "6c5riqgu0cspkp0ci56qlrh0b",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "geo": {
        "amazon_location_service": {
            "region": "us-east-1",
            "maps": {
                "items": {
                    "esristreet-main": {
                        "style": "VectorEsriStreets"
                    },
                    "esrinavigation-main": {
                        "style": "VectorEsriNavigation"
                    },
                    "esridarkgray-main": {
                        "style": "VectorEsriDarkGrayCanvas"
                    },
                    "esrilightgray-main": {
                        "style": "VectorEsriLightGrayCanvas"
                    },
                    "esriimagery-main": {
                        "style": "RasterEsriImagery"
                    },
                    "hereexolore-main": {
                        "style": "VectorHereExplore"
                    },
                    "heretruck-main": {
                        "style": "VectorHereExploreTruck"
                    },
                    "hereberlin-main": {
                        "style": "VectorHereBerlin"
                    },
                    "esrilight-main": {
                        "style": "VectorEsriTopographic"
                    }
                },
                "default": "esrilight-main"
            },
            "search_indices": {
                "items": [
                    "placeindex25da5c3c-main"
                ],
                "default": "placeindex25da5c3c-main"
            }
        }
    }
};


export default awsmobile;
