/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:157a1508-4000-41d9-8b63-33da98b65f31",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_3xxU94tG3",
    "aws_user_pools_web_client_id": "69apmdujff8qqmuiig4h5moa4k",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "geo": {
        "amazon_location_service": {
            "region": "ap-northeast-1",
            "maps": {
                "items": {
                    "esristreet-dev": {
                        "style": "VectorEsriStreets"
                    },
                    "esrinavigation-dev": {
                        "style": "VectorEsriNavigation"
                    },
                    "esridarkgray-dev": {
                        "style": "VectorEsriDarkGrayCanvas"
                    },
                    "esrilightgray-dev": {
                        "style": "VectorEsriLightGrayCanvas"
                    },
                    "esriimagery-dev": {
                        "style": "RasterEsriImagery"
                    },
                    "hereexolore-dev": {
                        "style": "VectorHereExplore"
                    },
                    "heretruck-dev": {
                        "style": "VectorHereExploreTruck"
                    },
                    "hereberlin-dev": {
                        "style": "VectorHereBerlin"
                    },
                    "esrilight-dev": {
                        "style": "VectorEsriTopographic"
                    }
                },
                "default": "esrilight-dev"
            },
            "search_indices": {
                "items": [
                    "placeindex25da5c3c-dev"
                ],
                "default": "placeindex25da5c3c-dev"
            }
        }
    }
};


export default awsmobile;
